### ISSUE TITLE
[Android Bootcamp] Pre-work: SimleTodo - Review my app

### ISSUE THREAD

**Issue by shz117** [shz117/SimpleTodo#1]
My app is complete, please review.  /cc @codepathreview @codepath

**Comment by nesquena** [comment]
Just confirming you are enrolled through Yahoo as "Hongzheng Shi"? Let me know if I mismatched.

Looks great! This was intended in part to give you an introduction to the general rhythm of this course. The course is entirely project based with an app being assigned each week and then due the following week. Each project builds on the last to help each engineer to learn all practical Android development and best practices as quickly as possible. We also do a code review for each submitted project once the program starts.

Nice job with the project, hope you found it as a helpful introduction and see you on Tuesday!

**Comment by shz117** [comment]
Hi @nesquena , thanks for confirming my assignment. And the name is correct. Should I expect in-person  class invitation? Because on yo/learning I still find myself in waitlist.
Thanks
Jeremy Hongzheng Shi

**Comment by nesquena** [comment]
Come to class and we will sort out the final attendees in person based on who has submitted pre-work.

**Comment by shz117** [comment]
Great! Thanks. See you later.
